name: SimplerBroadcast
version: 1.0.0
main: DerCommander610\Broadcast\Main
api: [4.17.1]

commands:
  broadcast:
    description: "Sende alle Spieler einen broadcast"
    permission: broadcast.cmd
permissions:
   broadcast.cmd:
      default: op 
